password: DOMBEE-EOMBE-DPBME-SPFBM-QPMBO-EMOVE
password2: Nts3yMJNBOhbrDas4rwQNVgdV71ZzCbu
password3: MARWAN-HLMDDA-KLSNHF-TRICKS-CCAIAM-DVQLKH
server: https://trickks.com/api
tool_name: JOINER
version: 1.5
